// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ext_mcp.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtMcp_CheckRequest_FullMethodName  = "/agentgateway.dev.ext_mcp.ExtMcp/CheckRequest"
	ExtMcp_CheckResponse_FullMethodName = "/agentgateway.dev.ext_mcp.ExtMcp/CheckResponse"
)

// ExtMcpClient is the client API for ExtMcp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExtMcp is the wire protocol for an MCP-aware external policy server.
// Modeled on Envoy ext_authz, but at the MCP method layer.
// Covers both gating and mutation.
type ExtMcpClient interface {
	CheckRequest(ctx context.Context, in *McpRequest, opts ...grpc.CallOption) (*McpRequestResult, error)
	CheckResponse(ctx context.Context, in *McpResponse, opts ...grpc.CallOption) (*McpResponseResult, error)
}

type extMcpClient struct {
	cc grpc.ClientConnInterface
}

func NewExtMcpClient(cc grpc.ClientConnInterface) ExtMcpClient {
	return &extMcpClient{cc}
}

func (c *extMcpClient) CheckRequest(ctx context.Context, in *McpRequest, opts ...grpc.CallOption) (*McpRequestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpRequestResult)
	err := c.cc.Invoke(ctx, ExtMcp_CheckRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extMcpClient) CheckResponse(ctx context.Context, in *McpResponse, opts ...grpc.CallOption) (*McpResponseResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpResponseResult)
	err := c.cc.Invoke(ctx, ExtMcp_CheckResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtMcpServer is the server API for ExtMcp service.
// All implementations must embed UnimplementedExtMcpServer
// for forward compatibility.
//
// ExtMcp is the wire protocol for an MCP-aware external policy server.
// Modeled on Envoy ext_authz, but at the MCP method layer.
// Covers both gating and mutation.
type ExtMcpServer interface {
	CheckRequest(context.Context, *McpRequest) (*McpRequestResult, error)
	CheckResponse(context.Context, *McpResponse) (*McpResponseResult, error)
	mustEmbedUnimplementedExtMcpServer()
}

// UnimplementedExtMcpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtMcpServer struct{}

func (UnimplementedExtMcpServer) CheckRequest(context.Context, *McpRequest) (*McpRequestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRequest not implemented")
}
func (UnimplementedExtMcpServer) CheckResponse(context.Context, *McpResponse) (*McpResponseResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckResponse not implemented")
}
func (UnimplementedExtMcpServer) mustEmbedUnimplementedExtMcpServer() {}
func (UnimplementedExtMcpServer) testEmbeddedByValue()                {}

// UnsafeExtMcpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtMcpServer will
// result in compilation errors.
type UnsafeExtMcpServer interface {
	mustEmbedUnimplementedExtMcpServer()
}

func RegisterExtMcpServer(s grpc.ServiceRegistrar, srv ExtMcpServer) {
	// If the following call panics, it indicates UnimplementedExtMcpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtMcp_ServiceDesc, srv)
}

func _ExtMcp_CheckRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtMcpServer).CheckRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtMcp_CheckRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtMcpServer).CheckRequest(ctx, req.(*McpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtMcp_CheckResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtMcpServer).CheckResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtMcp_CheckResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtMcpServer).CheckResponse(ctx, req.(*McpResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtMcp_ServiceDesc is the grpc.ServiceDesc for ExtMcp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtMcp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentgateway.dev.ext_mcp.ExtMcp",
	HandlerType: (*ExtMcpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRequest",
			Handler:    _ExtMcp_CheckRequest_Handler,
		},
		{
			MethodName: "CheckResponse",
			Handler:    _ExtMcp_CheckResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ext_mcp.proto",
}
