// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: ext_mcp.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationError_Code int32

const (
	AuthorizationError_UNKNOWN            AuthorizationError_Code = 0
	AuthorizationError_PERMISSION_DENIED  AuthorizationError_Code = 1
	AuthorizationError_RESOURCE_EXHAUSTED AuthorizationError_Code = 2
	AuthorizationError_INVALID            AuthorizationError_Code = 3
)

// Enum value maps for AuthorizationError_Code.
var (
	AuthorizationError_Code_name = map[int32]string{
		0: "UNKNOWN",
		1: "PERMISSION_DENIED",
		2: "RESOURCE_EXHAUSTED",
		3: "INVALID",
	}
	AuthorizationError_Code_value = map[string]int32{
		"UNKNOWN":            0,
		"PERMISSION_DENIED":  1,
		"RESOURCE_EXHAUSTED": 2,
		"INVALID":            3,
	}
)

func (x AuthorizationError_Code) Enum() *AuthorizationError_Code {
	p := new(AuthorizationError_Code)
	*p = x
	return p
}

func (x AuthorizationError_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationError_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_ext_mcp_proto_enumTypes[0].Descriptor()
}

func (AuthorizationError_Code) Type() protoreflect.EnumType {
	return &file_ext_mcp_proto_enumTypes[0]
}

func (x AuthorizationError_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationError_Code.Descriptor instead.
func (AuthorizationError_Code) EnumDescriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{7, 0}
}

type McpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend names this call targets, in their native (unmuxed) namespace.
	// Exactly one entry for single-target methods (`tools/call`, ...); one entry
	// per backend for fanout methods (e.g. `*/list`, ...).
	ServiceNames []string `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	// JSON-RPC method (e.g. "tools/call", "tools/list").
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// CEL-evaluated context from gateway config, one field per config key.
	MetadataContext *structpb.Struct `protobuf:"bytes,3,opt,name=metadata_context,json=metadataContext,proto3" json:"metadata_context,omitempty"`
	// JSON-RPC `params` as raw JSON bytes; absent when the method has none.
	McpRequest []byte `protobuf:"bytes,4,opt,name=mcp_request,json=mcpRequest,proto3,oneof" json:"mcp_request,omitempty"`
	// Incoming HTTP request headers carrying this MCP call, after gateway-side
	// allow/deny filtering. Multi-value headers appear as repeated entries with
	// the same key. Empty for stdio upstreams.
	Headers       []*McpHeader `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpRequest) Reset() {
	*x = McpRequest{}
	mi := &file_ext_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpRequest) ProtoMessage() {}

func (x *McpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpRequest.ProtoReflect.Descriptor instead.
func (*McpRequest) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *McpRequest) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

func (x *McpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *McpRequest) GetMetadataContext() *structpb.Struct {
	if x != nil {
		return x.MetadataContext
	}
	return nil
}

func (x *McpRequest) GetMcpRequest() []byte {
	if x != nil {
		return x.McpRequest
	}
	return nil
}

func (x *McpRequest) GetHeaders() []*McpHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type McpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend names this call targets, in their native (unmuxed) namespace.
	// Exactly one entry for single-target methods (`tools/call`, ...); one entry
	// per backend for fanout methods (e.g. `*/list`, ...).
	ServiceNames    []string         `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	Method          string           `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	MetadataContext *structpb.Struct `protobuf:"bytes,3,opt,name=metadata_context,json=metadataContext,proto3" json:"metadata_context,omitempty"`
	// JSON-RPC `result` from upstream as raw JSON bytes. Errors skip this hook.
	McpResponse   []byte `protobuf:"bytes,4,opt,name=mcp_response,json=mcpResponse,proto3" json:"mcp_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpResponse) Reset() {
	*x = McpResponse{}
	mi := &file_ext_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpResponse) ProtoMessage() {}

func (x *McpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpResponse.ProtoReflect.Descriptor instead.
func (*McpResponse) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *McpResponse) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

func (x *McpResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *McpResponse) GetMetadataContext() *structpb.Struct {
	if x != nil {
		return x.MetadataContext
	}
	return nil
}

func (x *McpResponse) GetMcpResponse() []byte {
	if x != nil {
		return x.McpResponse
	}
	return nil
}

type McpRequestResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*McpRequestResult_Pass
	//	*McpRequestResult_Mutated
	//	*McpRequestResult_Error
	Result isMcpRequestResult_Result `protobuf_oneof:"result"`
	// Mutations applied to the upstream HTTP request that carries this MCP call.
	// Honored on Pass and Mutated, ignored on Error and for stdio upstreams.
	HeaderMutation *HeaderMutation `protobuf:"bytes,4,opt,name=header_mutation,json=headerMutation,proto3" json:"header_mutation,omitempty"`
	// Arbitrary key/value bag stashed in request extensions and exposed to CEL as
	// `extMcp.<key>`. Subsequent backend filters (e.g. `transformation`) can read
	// from it. Honored on Pass and Mutated; merged with later processors' metadata.
	Metadata      *structpb.Struct `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpRequestResult) Reset() {
	*x = McpRequestResult{}
	mi := &file_ext_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpRequestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpRequestResult) ProtoMessage() {}

func (x *McpRequestResult) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpRequestResult.ProtoReflect.Descriptor instead.
func (*McpRequestResult) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *McpRequestResult) GetResult() isMcpRequestResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *McpRequestResult) GetPass() *Pass {
	if x != nil {
		if x, ok := x.Result.(*McpRequestResult_Pass); ok {
			return x.Pass
		}
	}
	return nil
}

func (x *McpRequestResult) GetMutated() []byte {
	if x != nil {
		if x, ok := x.Result.(*McpRequestResult_Mutated); ok {
			return x.Mutated
		}
	}
	return nil
}

func (x *McpRequestResult) GetError() *AuthorizationError {
	if x != nil {
		if x, ok := x.Result.(*McpRequestResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *McpRequestResult) GetHeaderMutation() *HeaderMutation {
	if x != nil {
		return x.HeaderMutation
	}
	return nil
}

func (x *McpRequestResult) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isMcpRequestResult_Result interface {
	isMcpRequestResult_Result()
}

type McpRequestResult_Pass struct {
	Pass *Pass `protobuf:"bytes,1,opt,name=pass,proto3,oneof"`
}

type McpRequestResult_Mutated struct {
	// Replaces JSON-RPC `params` before forwarding to the upstream MCP server.
	// The gateway does not re-run other RBAC on the mutated request.
	Mutated []byte `protobuf:"bytes,2,opt,name=mutated,proto3,oneof"`
}

type McpRequestResult_Error struct {
	Error *AuthorizationError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*McpRequestResult_Pass) isMcpRequestResult_Result() {}

func (*McpRequestResult_Mutated) isMcpRequestResult_Result() {}

func (*McpRequestResult_Error) isMcpRequestResult_Result() {}

type McpResponseResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*McpResponseResult_Pass
	//	*McpResponseResult_Mutated
	//	*McpResponseResult_Error
	Result        isMcpResponseResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpResponseResult) Reset() {
	*x = McpResponseResult{}
	mi := &file_ext_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpResponseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpResponseResult) ProtoMessage() {}

func (x *McpResponseResult) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpResponseResult.ProtoReflect.Descriptor instead.
func (*McpResponseResult) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *McpResponseResult) GetResult() isMcpResponseResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *McpResponseResult) GetPass() *Pass {
	if x != nil {
		if x, ok := x.Result.(*McpResponseResult_Pass); ok {
			return x.Pass
		}
	}
	return nil
}

func (x *McpResponseResult) GetMutated() []byte {
	if x != nil {
		if x, ok := x.Result.(*McpResponseResult_Mutated); ok {
			return x.Mutated
		}
	}
	return nil
}

func (x *McpResponseResult) GetError() *AuthorizationError {
	if x != nil {
		if x, ok := x.Result.(*McpResponseResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMcpResponseResult_Result interface {
	isMcpResponseResult_Result()
}

type McpResponseResult_Pass struct {
	Pass *Pass `protobuf:"bytes,1,opt,name=pass,proto3,oneof"`
}

type McpResponseResult_Mutated struct {
	// Replaces the JSON-RPC `result`. Raw JSON bytes; must parse as a valid
	// result for the method, else the gateway treats it as a protocol violation
	// per `failure_mode`.
	Mutated []byte `protobuf:"bytes,2,opt,name=mutated,proto3,oneof"`
}

type McpResponseResult_Error struct {
	Error *AuthorizationError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*McpResponseResult_Pass) isMcpResponseResult_Result() {}

func (*McpResponseResult_Mutated) isMcpResponseResult_Result() {}

func (*McpResponseResult_Error) isMcpResponseResult_Result() {}

type HeaderMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Headers to overwrite (insert if absent). If the same key is listed multiple
	// times it is treated as a list (all values replace the existing header).
	Set []*McpHeader `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty"`
	// Header names to remove (case-insensitive).
	Remove        []string `protobuf:"bytes,2,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderMutation) Reset() {
	*x = HeaderMutation{}
	mi := &file_ext_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMutation) ProtoMessage() {}

func (x *HeaderMutation) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMutation.ProtoReflect.Descriptor instead.
func (*HeaderMutation) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *HeaderMutation) GetSet() []*McpHeader {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *HeaderMutation) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type McpHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Raw value bytes: HTTP header values are not guaranteed to be UTF-8.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpHeader) Reset() {
	*x = McpHeader{}
	mi := &file_ext_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpHeader) ProtoMessage() {}

func (x *McpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpHeader.ProtoReflect.Descriptor instead.
func (*McpHeader) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *McpHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *McpHeader) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Pass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pass) Reset() {
	*x = Pass{}
	mi := &file_ext_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pass) ProtoMessage() {}

func (x *Pass) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pass.ProtoReflect.Descriptor instead.
func (*Pass) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{6}
}

type AuthorizationError struct {
	state  protoimpl.MessageState  `protogen:"open.v1"`
	Code   AuthorizationError_Code `protobuf:"varint,1,opt,name=code,proto3,enum=agentgateway.dev.ext_mcp.AuthorizationError_Code" json:"code,omitempty"`
	Reason string                  `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional explicit JSON-RPC error payload, as raw JSON bytes. Overrides the
	// code-derived default.
	McpError      []byte `protobuf:"bytes,3,opt,name=mcp_error,json=mcpError,proto3,oneof" json:"mcp_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationError) Reset() {
	*x = AuthorizationError{}
	mi := &file_ext_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationError) ProtoMessage() {}

func (x *AuthorizationError) ProtoReflect() protoreflect.Message {
	mi := &file_ext_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationError.ProtoReflect.Descriptor instead.
func (*AuthorizationError) Descriptor() ([]byte, []int) {
	return file_ext_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizationError) GetCode() AuthorizationError_Code {
	if x != nil {
		return x.Code
	}
	return AuthorizationError_UNKNOWN
}

func (x *AuthorizationError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuthorizationError) GetMcpError() []byte {
	if x != nil {
		return x.McpError
	}
	return nil
}

var File_ext_mcp_proto protoreflect.FileDescriptor

const file_ext_mcp_proto_rawDesc = "" +
	"\n" +
	"\rext_mcp.proto\x12\x18agentgateway.dev.ext_mcp\x1a\x1cgoogle/protobuf/struct.proto\"\x82\x02\n" +
	"\n" +
	"McpRequest\x12#\n" +
	"\rservice_names\x18\x01 \x03(\tR\fserviceNames\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12B\n" +
	"\x10metadata_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0fmetadataContext\x12$\n" +
	"\vmcp_request\x18\x04 \x01(\fH\x00R\n" +
	"mcpRequest\x88\x01\x01\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.agentgateway.dev.ext_mcp.McpHeaderR\aheadersB\x0e\n" +
	"\f_mcp_request\"\xb1\x01\n" +
	"\vMcpResponse\x12#\n" +
	"\rservice_names\x18\x01 \x03(\tR\fserviceNames\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12B\n" +
	"\x10metadata_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0fmetadataContext\x12!\n" +
	"\fmcp_response\x18\x04 \x01(\fR\vmcpResponse\"\xbc\x02\n" +
	"\x10McpRequestResult\x124\n" +
	"\x04pass\x18\x01 \x01(\v2\x1e.agentgateway.dev.ext_mcp.PassH\x00R\x04pass\x12\x1a\n" +
	"\amutated\x18\x02 \x01(\fH\x00R\amutated\x12D\n" +
	"\x05error\x18\x03 \x01(\v2,.agentgateway.dev.ext_mcp.AuthorizationErrorH\x00R\x05error\x12Q\n" +
	"\x0fheader_mutation\x18\x04 \x01(\v2(.agentgateway.dev.ext_mcp.HeaderMutationR\x0eheaderMutation\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadataB\b\n" +
	"\x06result\"\xb5\x01\n" +
	"\x11McpResponseResult\x124\n" +
	"\x04pass\x18\x01 \x01(\v2\x1e.agentgateway.dev.ext_mcp.PassH\x00R\x04pass\x12\x1a\n" +
	"\amutated\x18\x02 \x01(\fH\x00R\amutated\x12D\n" +
	"\x05error\x18\x03 \x01(\v2,.agentgateway.dev.ext_mcp.AuthorizationErrorH\x00R\x05errorB\b\n" +
	"\x06result\"_\n" +
	"\x0eHeaderMutation\x125\n" +
	"\x03set\x18\x01 \x03(\v2#.agentgateway.dev.ext_mcp.McpHeaderR\x03set\x12\x16\n" +
	"\x06remove\x18\x02 \x03(\tR\x06remove\"3\n" +
	"\tMcpHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x06\n" +
	"\x04Pass\"\xf4\x01\n" +
	"\x12AuthorizationError\x12E\n" +
	"\x04code\x18\x01 \x01(\x0e21.agentgateway.dev.ext_mcp.AuthorizationError.CodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\tmcp_error\x18\x03 \x01(\fH\x00R\bmcpError\x88\x01\x01\"O\n" +
	"\x04Code\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x01\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\x02\x12\v\n" +
	"\aINVALID\x10\x03B\f\n" +
	"\n" +
	"_mcp_error2\xcf\x01\n" +
	"\x06ExtMcp\x12`\n" +
	"\fCheckRequest\x12$.agentgateway.dev.ext_mcp.McpRequest\x1a*.agentgateway.dev.ext_mcp.McpRequestResult\x12c\n" +
	"\rCheckResponse\x12%.agentgateway.dev.ext_mcp.McpResponse\x1a+.agentgateway.dev.ext_mcp.McpResponseResultB1Z/github.com/agentgateway/agentgateway/go/api;apib\x06proto3"

var (
	file_ext_mcp_proto_rawDescOnce sync.Once
	file_ext_mcp_proto_rawDescData []byte
)

func file_ext_mcp_proto_rawDescGZIP() []byte {
	file_ext_mcp_proto_rawDescOnce.Do(func() {
		file_ext_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ext_mcp_proto_rawDesc), len(file_ext_mcp_proto_rawDesc)))
	})
	return file_ext_mcp_proto_rawDescData
}

var file_ext_mcp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ext_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ext_mcp_proto_goTypes = []any{
	(AuthorizationError_Code)(0), // 0: agentgateway.dev.ext_mcp.AuthorizationError.Code
	(*McpRequest)(nil),           // 1: agentgateway.dev.ext_mcp.McpRequest
	(*McpResponse)(nil),          // 2: agentgateway.dev.ext_mcp.McpResponse
	(*McpRequestResult)(nil),     // 3: agentgateway.dev.ext_mcp.McpRequestResult
	(*McpResponseResult)(nil),    // 4: agentgateway.dev.ext_mcp.McpResponseResult
	(*HeaderMutation)(nil),       // 5: agentgateway.dev.ext_mcp.HeaderMutation
	(*McpHeader)(nil),            // 6: agentgateway.dev.ext_mcp.McpHeader
	(*Pass)(nil),                 // 7: agentgateway.dev.ext_mcp.Pass
	(*AuthorizationError)(nil),   // 8: agentgateway.dev.ext_mcp.AuthorizationError
	(*structpb.Struct)(nil),      // 9: google.protobuf.Struct
}
var file_ext_mcp_proto_depIdxs = []int32{
	9,  // 0: agentgateway.dev.ext_mcp.McpRequest.metadata_context:type_name -> google.protobuf.Struct
	6,  // 1: agentgateway.dev.ext_mcp.McpRequest.headers:type_name -> agentgateway.dev.ext_mcp.McpHeader
	9,  // 2: agentgateway.dev.ext_mcp.McpResponse.metadata_context:type_name -> google.protobuf.Struct
	7,  // 3: agentgateway.dev.ext_mcp.McpRequestResult.pass:type_name -> agentgateway.dev.ext_mcp.Pass
	8,  // 4: agentgateway.dev.ext_mcp.McpRequestResult.error:type_name -> agentgateway.dev.ext_mcp.AuthorizationError
	5,  // 5: agentgateway.dev.ext_mcp.McpRequestResult.header_mutation:type_name -> agentgateway.dev.ext_mcp.HeaderMutation
	9,  // 6: agentgateway.dev.ext_mcp.McpRequestResult.metadata:type_name -> google.protobuf.Struct
	7,  // 7: agentgateway.dev.ext_mcp.McpResponseResult.pass:type_name -> agentgateway.dev.ext_mcp.Pass
	8,  // 8: agentgateway.dev.ext_mcp.McpResponseResult.error:type_name -> agentgateway.dev.ext_mcp.AuthorizationError
	6,  // 9: agentgateway.dev.ext_mcp.HeaderMutation.set:type_name -> agentgateway.dev.ext_mcp.McpHeader
	0,  // 10: agentgateway.dev.ext_mcp.AuthorizationError.code:type_name -> agentgateway.dev.ext_mcp.AuthorizationError.Code
	1,  // 11: agentgateway.dev.ext_mcp.ExtMcp.CheckRequest:input_type -> agentgateway.dev.ext_mcp.McpRequest
	2,  // 12: agentgateway.dev.ext_mcp.ExtMcp.CheckResponse:input_type -> agentgateway.dev.ext_mcp.McpResponse
	3,  // 13: agentgateway.dev.ext_mcp.ExtMcp.CheckRequest:output_type -> agentgateway.dev.ext_mcp.McpRequestResult
	4,  // 14: agentgateway.dev.ext_mcp.ExtMcp.CheckResponse:output_type -> agentgateway.dev.ext_mcp.McpResponseResult
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ext_mcp_proto_init() }
func file_ext_mcp_proto_init() {
	if File_ext_mcp_proto != nil {
		return
	}
	file_ext_mcp_proto_msgTypes[0].OneofWrappers = []any{}
	file_ext_mcp_proto_msgTypes[2].OneofWrappers = []any{
		(*McpRequestResult_Pass)(nil),
		(*McpRequestResult_Mutated)(nil),
		(*McpRequestResult_Error)(nil),
	}
	file_ext_mcp_proto_msgTypes[3].OneofWrappers = []any{
		(*McpResponseResult_Pass)(nil),
		(*McpResponseResult_Mutated)(nil),
		(*McpResponseResult_Error)(nil),
	}
	file_ext_mcp_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ext_mcp_proto_rawDesc), len(file_ext_mcp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ext_mcp_proto_goTypes,
		DependencyIndexes: file_ext_mcp_proto_depIdxs,
		EnumInfos:         file_ext_mcp_proto_enumTypes,
		MessageInfos:      file_ext_mcp_proto_msgTypes,
	}.Build()
	File_ext_mcp_proto = out.File
	file_ext_mcp_proto_goTypes = nil
	file_ext_mcp_proto_depIdxs = nil
}
